import React from 'react';
import './globals.css';
import Navbar from './components/Header/Navbar';

export const metadata = {
  title: 'Hello JVM!',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
